repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent=4
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-ast
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - --black
          - --wrap-summaries=120
          - --wrap-descriptions=120
          - --in-place
          - --pre-summary-newline
          - --close-quotes-on-newline

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --strict
          - --allow-untyped-decorators

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-rust
        args: [ --autofix ]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
